### ISSUE TITLE
AppImage generation fails

### ISSUE THREAD

**Issue by probonopd** [emericg/OffloadBuddy#1]
The AppImage generation and uploading currently fails due to

```
ERROR: ldd outputLine: "libavcodec.so.58 => not found"
ERROR: for binary: "/home/travis/build/emericg/OffloadBuddy/contribs/env/linux_x86_64/usr/lib/libavformat.so.58"
ERROR: Please ensure that all libraries can be found by ldd. Aborting.
```

Do a `export LD_LIBRARY_PATH=...` prior to invoking linuxdeployqt. Please let me know if you need further assistance. Thanks for making an AppImage available.

**Comment by emericg** [comment]
Hi!
Thanks for the feedback, it's weird it wasn't making the build fail.
So I rework the deploy_linux.sh script, and now it does fails properly ^^

> /usr/bin/ld: warning: libva.so.2, needed by /home/travis/build/emericg/OffloadBuddy/contribs/env/linux_x86_64/usr/lib//libavcodec.so, not found (try using -rpath or -rpath-link)

The right ffmpeg is used, but it depends on system libraries for HW decoding and now it can find these (libva-dev and libvdpau-dev are installed in the VM).
I tried to set `export LD_LIBRARY_PATH=$(pwd)/contribs/src/env/linux_x86_64/usr/lib/:$LD_LIBRARY_PATH;` but it doesn't seems to be working...

**Comment by probonopd** [comment]
Where is `libva.so.2` located on your build system? Need to set `LD_LIBRARY_PATH` to that, too.

**Comment by emericg** [comment]
Actually the problem is that travis CI only has libva.so.1 and my prebuilt ffmpeg is linked with the newer version...
So I guess my contribs script should do a proper ffmpeg build instead of using prebuilt binaries :-( that will take a bit more work, I'll leave this ticket open in the meantime.

**Comment by emericg** [comment]
Ok I fixed the ffmpeg deployment, but there is still issues left with some Qt plugins not working. The QtMultimedia player and the QtLocation services are silently failing. I have a couple of GStreamer warning messages and one "video output failed to load" (or something).

I copied the plugins in the app dir directory (plugins/mediaservice/*.so and plugins/geoservices/*.so) before running linuxdeployqt with -extra-plugins, but no luck... Any idea?

**Comment by probonopd** [comment]
Please run the application with `LD_DEBUG=libs ./Your.AppImage` and watch for any errors.

Is the AppImage available for download? Then I could have a look at it. Thanks.

**Comment by emericg** [comment]
Hi, yes the appimages are being uploaded again after each travis build.
Here is the latest (but transfer.sh seems down ATM): https://transfer.sh/bmG7D/OffloadBuddy-git.7c1a858-linux64.AppImage

I don't see many errors in the LD_DEBUG log, couple of qmlmemprofile_* symbols missing from libQt5Qml and one openGL error.

**Comment by probonopd** [comment]
Seems to run just fine on `xubuntu-18.04-desktop-amd64.iso`:

![](https://user-images.githubusercontent.com/2480569/50688526-bea39b80-101d-11e9-9411-8570bbf51c5b.png)

**Comment by emericg** [comment]
Yes the app run fine, that's why I closed the issue, but it's just the media player and maps that are "missing".
Anyway I'll figure it out eventually ^^

Thank you for your help, and great work with linuxdeployqt and AppImage, they are really awesome tools!
